### ISSUE TITLE
tcoh_view.py not working

### ISSUE THREAD

**Issue by Darumoso** [insarlab/MiaplPy#100]
I was trying to run `tcoh_view.py` but I get the next error:

```
Traceback (most recent call last):
  File "/home/doki/code/rsmas_insar/tools/MiaplPy/src/miaplpy/tcoh_view.py", line 18, in <module>
    from mintpy.utils import arg_group, ptime, time_func, readfile, plot as pp
ImportError: cannot import name 'arg_group' from 'mintpy.utils' (/home/doki/code/rsmas_insar/tools/MintPy/src/mintpy/utils/__init__.py)
```
This error shows even while trying to run `tcoh_view.py --help` or `tcoh_view.py -h`, I have the latest mintpy and miaplpy versions (Or at least, latest commits)

**Comment by Darumoso** [comment]
After the latest fix I get a new error:
```
  File "/home/doki/code/rsmas_insar/tools/miniforge3/bin/tcoh_view.py", line 5, in <module>
    from miaplpy.tcoh_view import main
  File "/home/doki/code/rsmas_insar/tools/MiaplPy/src/miaplpy/tcoh_view.py", line 187, in <module>
    class CoherenceViewer(tsview.timeseriesViewer):
AttributeError: module 'mintpy.cli.tsview' has no attribute 'timeseriesViewer'
```
Again, this error shows while trying to run `tcoh_view.py --help`
