### ISSUE TITLE
Module 'mintpy.load_data' has no attribute 'print_write_setting'

### ISSUE THREAD

**Issue by bjmarfito** [insarlab/MiaplPy#12]
After updating to the latest version of MintPy, a new error came up. After looking into it, the error was cause by the removal of the function `print_write_setting` in mintpy.load_data due to the PR https://github.com/insarlab/MintPy/pull/796/files#diff-99744ebb08e7cd1faee6bef21777ee1f3ce58975550918bd3213d804e6f6a502. I am stuck on how to properly addressed this new issue.

I attached below the error I encountered.

```
searching geometry files info
input data files:
height          : /home/data/INSAR_processing/bjm_ts/kalimantan/a1_stripmapstack/merged/geom_reference/hgt.rdr
latitude        : /home/data/INSAR_processing/bjm_ts/kalimantan/a1_stripmapstack/merged/geom_reference/lat.rdr
longitude       : /home/data/INSAR_processing/bjm_ts/kalimantan/a1_stripmapstack/merged/geom_reference/lon.rdr
incidenceAngle  : /home/data/INSAR_processing/bjm_ts/kalimantan/a1_stripmapstack/merged/geom_reference/los.rdr
azimuthAngle    : /home/data/INSAR_processing/bjm_ts/kalimantan/a1_stripmapstack/merged/geom_reference/los.rdr
shadowMask      : /home/data/INSAR_processing/bjm_ts/kalimantan/a1_stripmapstack/merged/geom_reference/shadowMask.rdr
Traceback (most recent call last):
  File "/home/bryanjim001/tools/MiaplPy/miaplpy/load_slc_geometry.py", line 222, in <module>
    main()
  File "/home/bryanjim001/tools/MiaplPy/miaplpy/load_slc_geometry.py", line 85, in main
    updateMode, comp, box, boxGeo = mld.print_write_setting(iDict)
AttributeError: module 'mintpy.load_data' has no attribute 'print_write_setting'
```

**Comment by mirzaees** [comment]
This is resolves now
