### ISSUE TITLE
Occasional in step 9 in  save_hdfeos5.py: key error: LON_REF1  

### ISSUE THREAD

**Issue by falkamelung** [insarlab/MiaplPy#29]
Occasionally I am getting this `LON_REF1` attribute error in the last step. For the Pichincha test data I don't get it. A couple of days ago it worked fine with this data but slight different parameters.
Any idea?

```
******************** step - hdfeos5 ********************
--------------------------------------------

save_hdfeos5.py /scratch2/05861/tg851601/MiamiSenAT48/miaplpy/network_single_reference/geo/geo_timeseries_demErr.h5 --tc /scratch2/05861/tg851601/MiamiSenAT48/miaplpy/network_single_reference/geo/geo_temporalCoheren
ce.h5 --asc /scratch2/05861/tg851601/MiamiSenAT48/miaplpy/network_single_reference/geo/geo_avgSpatialCoh.h5 -m /scratch2/05861/tg851601/MiamiSenAT48/miaplpy/network_single_reference/geo/geo_maskTempCoh.h5 -g /scratc
h2/05861/tg851601/MiamiSenAT48/miaplpy/network_single_reference/geo/geo_geometryRadar.h5 -t /scratch2/05861/tg851601/MiamiSenAT48/miaplpy/network_single_reference/smallbaselineApp.cfg
read options from template file: smallbaselineApp.cfg
Traceback (most recent call last):
  File "/work2/05861/tg851601/stampede2/test3_frontera/rsmas_insar/sources/MintPy/mintpy/cli/smallbaselineApp.py", line 213, in <module>
    main(sys.argv[1:])
  File "/work2/05861/tg851601/stampede2/test3_frontera/rsmas_insar/sources/MintPy/mintpy/cli/smallbaselineApp.py", line 208, in main
    run_smallbaselineApp(inps)
  File "/work2/05861/tg851601/stampede2/test3_frontera/rsmas_insar/sources/MintPy/mintpy/smallbaselineApp.py", line 1115, in run_smallbaselineApp
    app.run(steps=inps.runSteps)
  File "/work2/05861/tg851601/stampede2/test3_frontera/rsmas_insar/sources/MintPy/mintpy/smallbaselineApp.py", line 921, in run
    self.run_save2hdfeos5(sname)
  File "/work2/05861/tg851601/stampede2/test3_frontera/rsmas_insar/sources/MintPy/mintpy/smallbaselineApp.py", line 861, in run_save2hdfeos5
    mintpy.cli.save_hdfeos5.main(iargs)
  File "/work2/05861/tg851601/stampede2/test3_frontera/rsmas_insar/sources/MintPy/mintpy/cli/save_hdfeos5.py", line 107, in main
    save_hdfeos5(inps)
  File "/work2/05861/tg851601/stampede2/test3_frontera/rsmas_insar/sources/MintPy/mintpy/save_hdfeos5.py", line 437, in save_hdfeos5
    meta = prep_metadata(
  File "/work2/05861/tg851601/stampede2/test3_frontera/rsmas_insar/sources/MintPy/mintpy/save_hdfeos5.py", line 64, in prep_metadata
    unavco_meta = metadata_mintpy2unavco(meta, ts_obj.dateList, geom_file)
  File "/work2/05861/tg851601/stampede2/test3_frontera/rsmas_insar/sources/MintPy/mintpy/save_hdfeos5.py", line 118, in metadata_mintpy2unavco
    lons = [meta['LON_REF1'],
KeyError: 'LON_REF1'
Go back to directory: /scratch2/05861/tg851601/MiamiSenAT48/miaplpy

###############################################################

**Comment by falkamelung** [comment]
I had a messed up ice installation. Is not an issue. Closing
