### ISSUE TITLE
No slcStack.h5 with gamma processor

### ISSUE THREAD

**Issue by gongzhiqiang97** [insarlab/MiaplPy#45]
**There are always errors when i run as follows:**

miaplpyApp.py YuzhouSen.template --dostep load_data ./
--------------------------------------------------
........
.......
processor: gamma
Traceback (most recent call last):
  File "/home/sar02/tools/MiaplPy/miaplpy/miaplpyApp.py", line 801, in <module>
    main()
  File "/home/sar02/tools/MiaplPy/miaplpy/miaplpyApp.py", line 82, in main
    app.open()
  File "/home/sar02/tools/MiaplPy/miaplpy/miaplpyApp.py", line 176, in open
    self.date_list, self.num_pixels, self.metadata = read_initial_info(self.workDir, self.templateFile)
  File "/home/sar02/tools/MiaplPy/miaplpy/objects/utils.py", line 1221, in read_initial_info
    iDict = read_inps2dict(inps_loadSlc)
  File "/home/sar02/tools/MiaplPy/miaplpy/objects/utils.py", line 1293, in read_inps2dict
    shutil.copytree(reference_dir, out_reference)
  File "/home/sar02/anaconda3/envs/insar/lib/python3.8/shutil.py", line 555, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: ''

**here is my template:**
miaplpy.load.processor      = gamma
miaplpy.load.unwFile        = ./PROCESS/DONE/IFG*/diff* rlks.unw
miaplpy.load.corFile        = ./PROCESS/DONE/IFG* /* filt*rlks.cor
miaplpy.load.connCompFile   = None
miaplpy.load.intFile        = None

miaplpy.load.slcFile        = ./merged/SLC/* /*.slc.full  #[path2slc_file]

miaplpy.load.demFile        = ./PROCESS/SIM/sim_${m_date12}/sim*.hgt_sim
miaplpy.load.lookupYFile    = ./PROCESS/SIM/sim_${m_date12}/sim*.UTM_TO_RDC
miaplpy.load.lookupXFile    = ./PROCESS/SIM/sim_${m_date12}/sim*.UTM_TO_RDC
miaplpy.load.incAngleFile   = None
miaplpy.load.azAngleFile    = None
miaplpy.load.shadowMaskFile = None
miaplpy.load.bperpFile      = ./merged/baselines/* /* .base_perp

miaplpy.multiprocessing.numProcessor   = 4
miaplpy.interferograms.type = single_reference

mintpy.compute.cluster     = local  # if dask is not available, set this option to no
mintpy.compute.numWorker   = 8

how can i create the file of slcStack.h5?
**i have prepared all files of this needed and  checked all path, those are ok. so how can i solve this problem? hope your advice! thanks!**

**Comment by alejobeap** [comment]
HI 
I have the same problem I run the stack with ISCE but they dont found the slc.full in the folder.
In the SLC folder there are the *.slc.full.vrt and *slc.full.xml for each date.
Thanks
Alejandro

**Comment by mirzaees** [comment]
Hi @gongzhiqiang97 and @alejobeap 
Thank you for the pointing to the bug. Unfortunately I don't have data processed with gamma. It will be very helpful if you can provide me some sample data so I can test and debug the problem.

**Comment by alejobeap** [comment]
Thanks, but in my case I run the stack with ISCE2 with stackSentinel.py and according to the example template 
minopy.load.slcFile        = ../merged/SLC/*/*.slc.full  #[path2slc_file]
I only have the *.slc.full.vrt and *slc.full.xml for each date.

The message is:

File "/home/sar02/tools/MiaplPy/miaplpy/miaplpyApp.py", line 801, in
main()
File "/home/sar02/tools/MiaplPy/miaplpy/miaplpyApp.py", line 82, in main
app.open()
File "/home/sar02/tools/MiaplPy/miaplpy/miaplpyApp.py", line 176, in open
self.date_list, self.num_pixels, self.metadata = read_initial_info(self.workDir, self.templateFile)
File "/home/sar02/tools/MiaplPy/miaplpy/objects/utils.py", line 1221, in read_initial_info
iDict = read_inps2dict(inps_loadSlc)
File "/home/sar02/tools/MiaplPy/miaplpy/objects/utils.py", line 1293, in read_inps2dict
shutil.copytree(reference_dir, out_reference)
File "/home/sar02/anaconda3/envs/insar/lib/python3.8/shutil.py", line 555, in copytree
with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: ''


The same of @gongzhiqiang97 

Thanks

Alejandro

**Comment by esrivas17** [comment]
To get the "slc.full" files you need to edit the configs/config_merge_* files in your ISCE directory.
In each of these files you have several options to run `mergeBurst.py`, you only need to change the `use_virtual_files` flag to `False` and run it again.

**Comment by david-ncu2019** [comment]
Dear all,

I hope that someone can share how to obtain **slcStack.h5** after processing the `TerraSAR-X` and `Sentinel-1` images with **`ISCE`**. I cannot find any guidance from tutorials.

The purpose is to save the disk space by keeping necessary files only for further processing, since the output from ISCE may take 500 GB - 1 TB.

Thanks so much!
