### ISSUE TITLE
ImportError: cannot import name 'utils' from 'miaplpy.lib' (/mnt/d/SAR/MiaplPy/src/miaplpy/lib/__init__.py)

### ISSUE THREAD

**Issue by hzq2311** [insarlab/MiaplPy#65]
Hello,
 I install the new release version of miaplpy follow by docs/installation.md, and run it by example data. and It show an error as follow at step 2. It seems python could not found the module in miaplpy.lib.  How to fix it?

<><><><><><><><><> step 2 - phase_linking (MiaplPy) <><><><><><><><><><>
Generate /mnt/d/work/test/PichinchaSenDT142/miaplpy/network_single_reference/run_files/run_02_miaplpy_phase_linking
Total number of PATCHES: 27
Number of tasks for step phase inversion: 4
Traceback (most recent call last):
  File "/home/hzq/miniforge3/envs/miaplpy/bin/phase_linking.py", line 5, in <module>
    from miaplpy.phase_linking import main
  File "/mnt/d/SAR/MiaplPy/src/miaplpy/phase_linking.py", line 17, in <module>
    from miaplpy.lib import utils as iut
ImportError: cannot import name 'utils' from 'miaplpy.lib' (/mnt/d/SAR/MiaplPy/src/miaplpy/lib/__init__.py)
Traceback (most recent call last):
  File "/home/hzq/miniforge3/envs/miaplpy/bin/phase_linking.py", line 5, in <module>
    from miaplpy.phase_linking import main
  File "/mnt/d/SAR/MiaplPy/src/miaplpy/phase_linking.py", line 17, in <module>
    from miaplpy.lib import utils as iut
ImportError: cannot import name 'utils' from 'miaplpy.lib' (/mnt/d/SAR/MiaplPy/src/miaplpy/lib/__init__.py)
Traceback (most recent call last):
  File "/home/hzq/miniforge3/envs/miaplpy/bin/phase_linking.py", line 5, in <module>
    from miaplpy.phase_linking import main
  File "/mnt/d/SAR/MiaplPy/src/miaplpy/phase_linking.py", line 17, in <module>
    from miaplpy.lib import utils as iut
ImportError: cannot import name 'utils' from 'miaplpy.lib' (/mnt/d/SAR/MiaplPy/src/miaplpy/lib/__init__.py)
Traceback (most recent call last):
  File "/home/hzq/miniforge3/envs/miaplpy/bin/phase_linking.py", line 5, in <module>
    from miaplpy.phase_linking import main
  File "/mnt/d/SAR/MiaplPy/src/miaplpy/phase_linking.py", line 17, in <module>
    from miaplpy.lib import utils as iut
ImportError: cannot import name 'utils' from 'miaplpy.lib' (/mnt/d/SAR/MiaplPy/src/miaplpy/lib/__init__.py)
Go back to directory: /mnt/d/work/test/PichinchaSenDT142/miaplpy

###############################################################
Normal end of Non-Linear time series processing workflow!
##############################################################
Go back to directory: /mnt/d/work/test/PichinchaSenDT142/miaplpy

**Comment by hzq2311** [comment]
I fix it by configure bash environment
