### ISSUE TITLE
KeyError: 'width' for load_ifgram (MiaplPy)

### ISSUE THREAD

**Issue by mqd-lufei** [insarlab/MiaplPy#75]
when i run "miaplpy.interferograms.networkType = delaunay" , the following error occurs. I don't know why will appear this mistake, because there is no error operation "miaplpy.interferograms.net workType = single_reference"

<><><><><><><><><> step 6 - load_ifgram (MiaplPy) <><><><><><><><><><>
Generate /home/gmtsar-user/test/LuD/Process/miaplpy/network_delaunay_4/run_files/run_06_miaplpy_load_ifgram
20240102:231249 * load_ifgram.py --template /home/gmtsar-user/test/LuD/Process/miaplpy/miaplpyApp.cfg /home/gmtsar-user/test/LuD/Process/LUD --project LUD --output /home/gmtsar-user/test/LuD/Process/miaplpy/network_delaunay_4/inputs/ifgramStack.h5 /home/gmtsar-user/test/LuD/Process/miaplpy/network_delaunay_4/inputs/geometryRadar.h5 /home/gmtsar-user/test/LuD/Process/miaplpy/network_delaunay_4/inputs/geometryGeo.h5
SAR platform/sensor : unknown from project name "LUD"
check auto path setting for Univ of Miami users for processor: isce
--------------------------------------------------
prepare metadata files for isce products
['../reference/data.rsc'] exists and is newer than ['../reference/IW1.xml'] --> skip.
preparing RSC file for geometry files
write file: /home/gmtsar-user/test/LuD/Process/merged/geom_reference/shadowMask.rdr.rsc
read perp baseline time-series from ../baselines
preparing RSC file for: ./inverted/interferograms_delaunay/*/*fine*.unw
Traceback (most recent call last):
  File "/home/gmtsar-user/Softwares/MiaplPy/src/miaplpy/load_ifgram.py", line 474, in <module>
    main()
  File "/home/gmtsar-user/Softwares/MiaplPy/src/miaplpy/load_ifgram.py", line 359, in main
    inpsDict = read_subset_box(inpsDict)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmtsar-user/Softwares/MiaplPy/src/miaplpy/load_ifgram.py", line 250, in read_subset_box
    pix_box = (0, 0, int(atr['width']), int(atr['length']))    # coord.bbox_geo2radar(geo_box)
                         ~~~^^^^^^^^^
KeyError: 'width'

**Comment by mqd-lufei** [comment]
I solved this issue because I was unfamiliar with the folder naming rules that caused this problem. When you use other network types, be careful to set the correct path in your configuration parameter file. For example:
when you run "miaplpy.interferograms.networkType = delaunay", please set "miaplpy.load.unwFile        = ./inverted/interferograms_delaunay_4/*/*fine*.unw" instead of "miaplpy.load.unwFile        = ./inverted/interferograms_delaunay/*/*fine*.unw"
