### ISSUE TITLE
ValueError: Buffer dtype mismatch, expected 'int' but got 'bool'

### ISSUE THREAD

**Issue by weizhenlwz** [insarlab/MiaplPy#81]
<><><><><><><><><> step 2 - phase_linking (MiaplPy) <><><><><><><><><><>
Generate /panda/linwz/shili/PichinchaSenDT142/miaplpy/network_single_reference/run_files/run_02_miaplpy_phase_linking
Total number of PATCHES: 27
Number of tasks for step phase inversion: 1
Traceback (most recent call last):
  File "/home/linwz/tools/mambaforge/envs/insar/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/linwz/tools/mambaforge/envs/insar/lib/python3.11/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "src/miaplpy/lib/utils.pyx", line 1063, in miaplpy.lib.utils.process_patch_c
ValueError: Buffer dtype mismatch, expected 'int' but got 'bool'

In fact, File "src/miaplpy/lib/utils.pyx" without a error，But file“envs/../lib/python3.11/site-packages/miaplpy/lib”  is an error, need to recompile

**Comment by zamuzakki** [comment]
Hi @weizhenlwz . I got this type of issue when installing miaplply from main branch. I solved it by installing specific version [V0.2.1](https://github.com/insarlab/MiaplPy/releases/tag/V0.2.1).
