### ISSUE TITLE
Buffer type mismatch error in phase_linking.py --concatenate

### ISSUE THREAD

**Issue by falkamelung** [insarlab/MiaplPy#82]
I am now getting this error in run_03 step (after the fix from earlier today)

```
--------------------------------------------------
Concatenate block 29/30 : [1800  400 1905  524]
close HDF5 file phase_series.h5.
write amplitude dispersion and top eigen values
write averaged temporal coherence file from mini stacks
write PS mask file
Traceback (most recent call last):
  File "/work2/05861/tg851601/stampede2/code/rsmas_insar/tools/miniconda3/bin/phase_linking.py", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/work2/05861/tg851601/stampede2/code/rsmas_insar/tools/MiaplPy/src/miaplpy/phase_linking.py", line 54, in main
    concatenate_patches(inversionObj)
  File "/work2/05861/tg851601/stampede2/code/rsmas_insar/tools/MiaplPy/src/miaplpy/phase_linking.py", line 147, in concatenate_patches
    inversionObj.unpatch()
  File "src/miaplpy/lib/invert.pyx", line 486, in miaplpy.lib.invert.CPhaseLink.unpatch
  File "src/miaplpy/lib/invert.pyx", line 491, in miaplpy.lib.invert.CPhaseLink.unpatch
ValueError: Buffer dtype mismatch, expected 'int' but got 'bool'
```

**Comment by mirzaees** [comment]
Thanks @falkamelung 
resolved in #83
