### ISSUE TITLE
ImportError: cannot import name 'utils' from 'miaplpy.lib'

### ISSUE THREAD

**Issue by AuRevoirzzz** [insarlab/MiaplPy#92]
Hi, @zamuzakki 
I install the new release version of miaplpy follow by installation.md, and run it by example data. And it show an error as follow at step 2. How to fix it?
MiaplPy version V0.2.1-14, date 2024-04-04

```
<><><><><><><><><> step 2 - phase_linking (MiaplPy) <><><><><><><><><><>

Generate /media/aurevoir/data/PichinchaSenDT142/miaplpy/network_single_reference/run_files/run_02_miaplpy_phase_linking
Total number of PATCHES: 27
Number of tasks for step phase inversion: 1
Traceback (most recent call last):
  File "/home/aurevoir/tools/miniforge/envs/insar/bin/phase_linking.py", line 5, in <module>
    from miaplpy.phase_linking import main
  File "/home/aurevoir/tools/MiaplPy/src/miaplpy/phase_linking.py", line 17, in <module>
    from miaplpy.lib import utils as iut
ImportError: cannot import name 'utils' from 'miaplpy.lib' (/home/aurevoir/tools/MiaplPy/src/miaplpy/lib/__init__.py)
Go back to directory: /media/aurevoir/data/PichinchaSenDT142/miaplpy
``` 
This is my environment 
```
export MIAPLPY_HOME=/home/aurevoir/tools/MiaplPy
export PATH=${PATH}:${MIAPLPY_HOME}/src/miaplpy
export PYTHONPATH=${PYTHONPATH}:${MIAPLPY_HOME}/src
```

**Comment by AuRevoirzzz** [comment]
This is my environment
```
# miaplpy #
export MIAPLPY_HOME=/home/aurevoir/tools/MiaplPy
export PATH=${PATH}:${MIAPLPY_HOME}/src/miaplpy
export PYTHONPATH=${PYTHONPATH}:${MIAPLPY_HOME}
```
